### ISSUE TITLE
.tsx 文件 sourceMap 失效

### ISSUE THREAD

**Issue by luhc228** [raxjs/rax-app#1009]
## What is the expected behavior?**
表现是 rax-app 本地调试的时候，在组件中加了 debugger 却跳到 ErrorBoundaryFallback 组件
![image](https://user-images.githubusercontent.com/44047106/174737705-a6a94745-b7c7-4c2d-8e59-0dcd0c9f9851.png)

## Any additional comments?

- **rax-app Version**：3.8.x
- **build.json Configuration**：
```json
{
  "targets": ["web"],
  "web": {
    "mpa": true,
    "pha": true
  },
  "plugins": [
    "@ali/build-plugin-rax-app-def",
    [
      "@ali/build-plugin-event-tracking-register",
      {
        "goldlog": false
      }
    ]
  ]
}
```
- **Node Version**:16
- **Platform**:mac

**Comment by wssgcg1213** [comment]
目前排查到的信息：

> babel-core 的 remap 机制发生改变了
> 之前基于 sourcemap 的没问题，后来基于 @ampproject/remapping 的就有问题了

> ts-loader 中会把 loaderContext.remainingRequest 设置到 sources 里，这时 remainingRequest 里会带上 rax-platform-loader 的路径
> 如果 ts-loader 和 rax-platform-loader 换下位置，应该也可以了的
