### ISSUE TITLE
Terser Plugin 在开启 webpack 5 后报错

### ISSUE THREAD

**Issue by ClarkXia** [raxjs/rax-app#1019]
![image](https://user-images.githubusercontent.com/4219965/189284358-4a967ad4-25e9-472b-a6d5-cd4be366251e.png)

在复杂的项目中开启 webpack 5 后会出现报错，需要确认下 Terser webpack 插件在开启 webpack 5 后使用的版本是否锁定

**Comment by wssgcg1213** [comment]
本地构建通过, 但是云构建有问题, 经确认是 def 插件注册的问题, 升级到 4.x 解决
