### ISSUE TITLE
build.json里outputDir设置后，部分文件依然输出在默认文件夹内

### ISSUE THREAD

**Issue by RossYan86** [raxjs/rax-app#461]
{
  "targets": [
    "wechat-miniprogram"
  ],
  "outputDir": "dist/build",
  "plugins": []
}
这样设置后，输出如下图
![image](https://user-images.githubusercontent.com/35550069/96992373-645e2c80-155c-11eb-8e66-cd3b6e06a72a.png)

还有个build.json小问题，IDE一直有个提示，如下图
![image](https://user-images.githubusercontent.com/35550069/96992544-9ff8f680-155c-11eb-9798-17038433d249.png)

**Comment by SoloJiang** [comment]
https://github.com/raxjs/rax-app/pull/494
