### ISSUE TITLE
PHA 模板化能力

### ISSUE THREAD

**Issue by boiawang** [raxjs/rax-app#478]
### 开启 PHA
在 `build.json` 中配置开启 PHA，开启 PHA 以后，会在 build 目录下生成 `manifest.json` 和 `app-worker.js`。

```json
{
  "web": {
    "pha": true
  }
}
```

### 开启模板化能力

开启模板化能力后在端内加载 html 的时候可以做到不请求网络，并且会内置多个公共的 JS(lib-windvane/3.0.7、lib-mtop/2.6.1、tracker/5.0.4、aplus/8.14.6 等)

```json
{
  "web": {
    "pha": {
      "template": true
    }
  }
}
```

### 覆盖内置的 JS

在脚手架中会有默认的内置 JS，可以在 build.json 中定义希望覆盖的版本：

```json
{
  "web": {
    "pha": {
      "template": {
        "customBuiltInScript": {
            "windvane": "https://g.alicdn.com/mtb/lib-windvane/3.0.7/windvane.js"
        }
      }
    }
  }
}
```

### 覆盖内置的文档

是否使用项目中的 document.jsx 代替客户端内置的文档，需要定制 document 的业务可以如下配置：

```json
{
  "web": {
    "pha": {
      "template": {
        "useDocument": true
      }
    }
  }
}
```

**Comment by SoloJiang** [comment]
https://github.com/raxjs/rax-app/issues/513 直接在这里讨论吧
