### ISSUE TITLE
rax-scripts 仓库整理迁移计划

### ISSUE THREAD

**Issue by SoloJiang** [raxjs/rax-app#481]
## 项目目录
目录结构参考 icejs

## 新增包
- build-plugin-rax-web
- build-plugin-rax-miniapp
- build-plugin-rax-weex
- build-plugin-rax-kraken
- rax-app
- rax-app-renderer

## 保留的包
- babel-plugin-transform-jsx-stylesheet
- babel-plugin-transform-jsx-to-html
- create-rax
- error-stack-tracey
- image-source-loader
- rax-platform-loader
- build-plugin-midway-faas
- build-plugin-rax-api-builder
- build-plugin-rax-app
- build-plugin-rax-compat-react
- build-plugin-rax-faas
- build-plugin-rax-fc
- build-plugin-rax-now
- build-plugin-rax-pha
- postcss-plugin-rpx2vw
- rax-babel-config
- rax-webpack-config
- rax-jest-config
- rax-cli
- stylesheet-loader

## 移除的包
- build-plugin-multi-demo-portal
- build-plugin-rax-block
- build-plugin-rax-miniapp-plugin
- build-plugin-rax-multi-pages
- build-plugin-rax-ssr
- build-plugin-rax-component
- build-plugin-rax-theme
- eslint-config-rax
- eslint-plugin-module
- jsx2mp-cli
- jsx2mp-loader
- miniapp-builder-shared
- miniapp-compile-config
- miniapp-runtime-config
- rax-hot-module-replacement-webpack-plugin
- rax-miniapp-babel-plugins
- rax-miniapp-config-webpack-plugin
- rax-miniapp-runtime-webpack-plugin
- rax-multi-pages-settings
- rax-quickapp-webpack-plugin

## 仓库包文件夹命名规范
- build-scripts 插件命名为 `plugin-xxx`
- 构建相关包命名为 `build-xxx`
- loader 直接使用包名

**Comment by imsobear** [comment]
- rax-api-builder 是啥
- error-stack-tracey 职责
- image-source-loader 职责

**Comment by SoloJiang** [comment]
build-plugin-rax-api-builder 给 universal-env 用的
error-stack-tracey 根据 source map 确定错误栈
image-source-loader 老工程的依赖，用来将引入的图片转换为 { uri: base64, width, height }
