### ISSUE TITLE
字符串中包含 数字+rpx会被自动转成vw

### ISSUE THREAD

**Issue by divcris** [raxjs/rax-app#495]
![image](https://user-images.githubusercontent.com/15650165/99391320-03383780-2915-11eb-9af9-ae4af8187f44.png)

**Comment by huangjian008** [comment]
dom元素style里，字符串中包好数字+rpx这样的连续字符串单元，会变成vw单位

**Comment by SoloJiang** [comment]
https://github.com/alibaba/rax/pull/2040

**Comment by SoloJiang** [comment]
等双十二之后再发布

**Comment by SoloJiang** [comment]
Fixed
