### ISSUE TITLE
关于  build-plugin-rax-app 插件中，无法与其它插件共享 context

### ISSUE THREAD

**Issue by crazybear** [raxjs/rax-app#537]
build-plugin-rax-app@6.0.2

其中
applyUserConfig 中修改了当前 插件中 api 的 context
https://github.com/alibaba/ice/blob/master/packages/build-user-config/src/utils/modifyUserConfig.js#L34
导致无法与其它插件共享 context

例如在后续插件中，新增一个 userConfig,  build-plugin-rax-app 无法正确的获取到

**Comment by SoloJiang** [comment]
待 build scripts 发版后，修复问题
