### ISSUE TITLE
MPA 场景下页面组件使用 runApp 的能力

### ISSUE THREAD

**Issue by imsobear** [raxjs/rax-app#543]
目前 runApp 是跟 SPA 绑定在一起的，只有整个应用是 SPA 或者某个页面自身是 SPA 时才能使用 runApp，但是 runApp 提供的有的能力跟 SPA 并不绑定，MPA 里的每个页面是否也能直接使用这些能力？

**Comment by SoloJiang** [comment]
从使用上来看，这种模式是针对 `runApp` 的情况，在这种时候，还是需要 `routes` 字段告知用户要渲染哪一个组件，所以这个优化应该是针对 `routes` 长度为 1，且 `path: '/'` 的情况？

**Comment by imsobear** [comment]
单纯渲染一个组件，但是想使用 runApp 的某些能力（比如生命周期？），可以评估下

**Comment by imsobear** [comment]
我们可以梳理下目前 app.js 提供了哪些能力，其中哪些是跟前端路由无关的，这些能力 MPA 场景下可能是需要的。 @SoloJiang

**Comment by SoloJiang** [comment]
重复 https://github.com/alibaba/ice/issues/4384
