### ISSUE TITLE
Rax 应用模式梳理

### ISSUE THREAD

**Issue by imsobear** [raxjs/rax-app#557]
## SPA

```bash
├── src/                          
│   ├── pages/                     
│   ├── models/                    
│   ├── global.scss                
│   ├── store.ts                  
│   ├── app.json                  
│   └── app.ts  
```

## MPA

```bash
├── src/                          
│   ├── pages/                                       
│        ├── Dashboard/      
│        │     ├── app.js    
│        ├── List/       
│        │     ├── listA/index.jsx 
│        │     ├── listB/index.jsx 
│        │     ├── store.js 
│        │     ├── app.js    
│        │     └── app.json  
│        ├── About/           
│        │     ├── store.js     
│        │     └── index.jsx                           
│   └── app.json
```

单个页面的几个形式：

### 1. 单组件，对应 About

- `StoreProvider` 没有包裹上，需要手动包裹
- 必须有 `src/app.ts`，没有就报错

### 2. SPA，对应 List

app.js + app.json，报错

![image](https://user-images.githubusercontent.com/2505411/103335803-27a93700-4ab1-11eb-986c-0cc66117e95c.png)

### 3. app.js 单组件，对应 Dashboard

目前不支持，icejs 也不支持 https://github.com/alibaba/ice/issues/3945
 
其他问题：

- `src/global.scss` 目前有效吗？是否应该有效？

**Comment by SoloJiang** [comment]
https://github.com/raxjs/rax-app/issues/465

**Comment by SoloJiang** [comment]
2 的图挂了，src/global.scss 建议在 MPA 下每个页面都注入，收益是能更加丰富内置 HTML 的模版的场景，同时也能丰富自定义 Document 的场景

**Comment by SoloJiang** [comment]
1 里面没有 src/app.ts 报错的问题需要在改造 Document 架构的时候做，之前尝试修复发现改动太大

**Comment by imsobear** [comment]
> 都注入，收益是能更加丰富内置 HTML 的模版的场景，同时也能丰富自定义 Document 的场景

这个点可以再评估下，感觉收益不大，现在框架有的地方太复杂了导致 bug 频发，建议新功能的节奏放慢点，把已有功能做稳做精。 @ClarkXia @SoloJiang

**Comment by SoloJiang** [comment]
## MPA

### pages/Home/entry:

检测入口文件中是否存在 `export default` ，如果不存在说明是自定义 `render`。 

```
// 有 store 就包 provider，会生成 .rax/mpaEntry
export default function App() {}

// 不包 provider
render(<App/>);
```



### pages/Home/app:

不自动包裹 Provider。

**根目录下 app.json:**

```json
{
  "routes": [
    {
      "source": "pages/Home/app"
    }
  ]
}
```

**pages/Home 下 app.js**

```js
import staticConfig from './app.json';
import store from './store';

runApp({
  app: {
    addProvider: ({ children }) => {
       return <store.Provider>{children}</store.Provider>;
    }
  }
}, staticConfig);
```

**Comment by SoloJiang** [comment]
> ## MPA
> ### pages/Home/entry:
> 检测入口文件中是否存在 `export default` ，如果不存在说明是自定义 `render`。
> 
> ```
> // 有 store 就包 provider，会生成 .rax/mpaEntry
> export default function App() {}
> 
> // 不包 provider
> render(<App/>);
> ```
> 
> ### pages/Home/app:
> 不自动包裹 Provider。
> 
> **根目录下 app.json:**
> 
> ```json
> {
>   "routes": [
>     {
>       "source": "pages/Home/app"
>     }
>   ]
> }
> ```
> 
> **pages/Home 下 app.js**
> 
> ```js
> import staticConfig from './app.json';
> import store from './store';
> 
> runApp({
>   app: {
>     addProvider: ({ children }) => {
>        return <store.Provider>{children}</store.Provider>;
>     }
>   }
> }, staticConfig);
> ```
