### ISSUE TITLE
 强制保存了依赖node_modules 包的文件，但 node_modules 的修改并没有生效

### ISSUE THREAD

**Issue by tanyafuzhou** [raxjs/rax-app#560]
问题：
1. rax app 本地 tnpm run start ,node_modules内容修改后，需要 重新执行  tnpm run start  ，修改的内容才能生效
2. 强制保存了依赖 node_modules 包的文件，但 node_modules中 的修改并没有生效

**Comment by SoloJiang** [comment]
可以在 build.json 中配置：
```
{
  "devServer": {
     "watchOptions": {
        "ignored": []
     }
   }
}
```

rax-app 默认会忽略监听 node_modules 的热更新，以此避免额外的内存占用
