### ISSUE TITLE
Rax 应用创建选项优化

### ISSUE THREAD

**Issue by imsobear** [raxjs/rax-app#561]
## 背景

目前选项过多，看起来很灵活，但是很容易搞错，比如组合出小程序 + MPA、Weex + SPA 这种不推荐的类型。

## 优化方案

多个组合选项合并成一个：

- Web + MPA（默认开启 PHA，**是否有副作用**）
- 小程序（默认支持 Web+SPA，**默认开启支付宝和微信都开启吗？**）
- Weex + MPA（开启 Web + MPA）
- Kraken + MPA（开启 Web + MPA）
- Web + SPA（备注：手淘等 App 场景不推荐）

Kraken 和 Weex 暂时不考虑 SPA。

## 相关改造

- [x] plugin-def 3.0.0 插件发版
- [ ] generator-project 发版 https://github.com/ice-lab/iceworks-cli/pull/100
- [ ] rax-materials 发版 https://github.com/raxjs/rax-materials/pull/37
- 初始化链路改造：
  - [ ] rax-cli https://github.com/raxjs/rax-app/pull/563
  - [ ] DEF generator cf
  - [ ] Iceworks Create Project

**Comment by SoloJiang** [comment]
小程序分包 + MPA

**Comment by imsobear** [comment]
> 小程序分包 + MPA

场景不多吧，感觉没必要作为前置的一个选项，类似我们现在提供的 MPA 也很轻量，也不包含各种类型的 case。

**Comment by ChrisCindy** [comment]
1. 小程序如果默认全选，构建速度是个挑战，后面再加上头条百度等端，可能问题会更大。

2. 另外小程序分包场景下代码结构改动比较大，可以考虑脚手架生成一个默认的模板？

3. 小程序可以把默认生成模板改成双引擎的，即运行时壳+编译时组件，从模板上引导用户走双引擎结合方式开发

**Comment by SoloJiang** [comment]
> 1. 小程序如果默认全选，构建速度是个挑战，后面再加上头条百度等端，可能问题会更大。
> 2. 另外小程序分包场景下代码结构改动比较大，可以考虑脚手架生成一个默认的模板？
> 3. 小程序可以把默认生成模板改成双引擎的，即运行时壳+编译时组件，从模板上引导用户走双引擎结合方式开发

2. 感觉和 MPA 的模板是一样的
3. 现在要开启双引擎也只用新增一个文件夹就够了？

**Comment by imsobear** [comment]
1. 默认就开启支付宝和微信，其他的需要手动加
2. 如果有必要可以有单独的模板
