### ISSUE TITLE
组件创建链路选项优化

### ISSUE THREAD

**Issue by imsobear** [raxjs/rax-app#587]
类似 issue #561

**Comment by ChrisCindy** [comment]
现有方案：
- 用户选择创建组件工程
- 选择端（Web、Alibaba MiniApp、WeChat MiniProgram、Kraken）
- 语言选择（JS、TS）

优化后方案：

TODO

**Comment by imsobear** [comment]
@ChrisCindy 方案没有问题，这两周支持掉吧

**Comment by ChrisCindy** [comment]
> @ChrisCindy 方案没有问题，这两周支持掉吧

OK
