### ISSUE TITLE
postcss-plugin-rpx2vw 转换px逻辑有误。

### ISSUE THREAD

**Issue by julytang** [raxjs/rax-app#602]
## 发生了什么?
postcss-plugin-rpx2vw在以下配置的情况下
"rpxOptions": {
      "viewportWidth": 375, 
      "viewportUnit": "px",
      "fontViewportUnit": "px", 
      "unitPrecision": 5
    },
设置viewportUnit为px的情况下，转换单位逻辑依然是按照vw进行转换，只是在转换完vw之后对单位进行替换，不符合预期。

## 期望的结果是什么
viewportWidth设置为375时，如果设置viewportUnit为vw，那么应该得到200vw。设置viewportUnit为px时应该得到375px。

## 相关环境信息

- **rax-app 版本**：1.2.0
- **build.json 配置**：```
{
  "plugins": [
    [
      "build-plugin-rax-halo-component",
      {
        "type": "rax",
        "targets": ["web", "miniapp", "wechat-miniprogram"],
        "miniapp": {
          "buildType": "runtime"
        },
        "wechat-miniprogram": {
          "buildType": "runtime" 
        },
        "esOutputDir": "es",
        "typesOutputDir": "types"
      }
    ]
  ]
}
```
- **Node 版本**：12
- **操作系统**：macOs 11.1

**Comment by SoloJiang** [comment]
从插件逻辑来看没有问题，你看到的转换失败是运行时的，还是构建结果有问题

**Comment by julytang** [comment]
> 从插件逻辑来看没有问题，你看到的转换失败是运行时的，还是构建结果有问题

750rpx如果按照viewportWidth为375来看，如果单位是vw，那么得到的结果应该是200vw，这个是OK的，如果375单位是px的话，那么应该是得到375px。但是得到的结果是200px。转换逻辑只有针对vw的处理，没有针对px做处理，这是不合理的。

**Comment by SoloJiang** [comment]
嗯，我看到了，如果是这种场景是不是不应该用 `postcss-plugin-rpx2vw` 这个插件，而是 `postcss-plugin-rpx2px` ？

**Comment by SoloJiang** [comment]
本质上 `rpx` 和 `vw` 都是响应式单位，区别只是屏幕切割份数的不同，而 `px` 是物理像素，和屏幕比例没有什么关系

**Comment by julytang** [comment]
> 本质上 `rpx` 和 `vw` 都是响应式单位，区别只是屏幕切割份数的不同，而 `px` 是物理像素，和屏幕比例没有什么关系

的确px跟以上两者有区别。但是这个插件提供了指定的viewportUnit，我理解插件在设计之初是考虑到了这个场景。
其次，rax作为多端方案，应该也是需要考虑除了端上的webview渲染以外的pc浏览器渲染场景。
目前，在前端领域搭建是一个很多人关注的方向，在搭建侧，往往需要将页面渲染在视图中的某个位置，这个时候vw是不满足需求的。

**Comment by SoloJiang** [comment]
Rax 目前对 PC 这边的兼容还比较弱，主要还是无线端，搭建侧目前不是我们重点投入的领域，你可以尝试使用 iframe 的方案，或者更好的可以给我们提 PR 以及 RFC，通过生态的方式来支持

**Comment by julytang** [comment]
那可以开放这个plugin的仓库吗，我可以提交pr或者是我自己folk。

**Comment by SoloJiang** [comment]
代码就在这个仓库里
