### ISSUE TITLE
[Feature] 添加 `injectServerSideData ` 字段关闭默认注入 initialData 的行为

### ISSUE THREAD

**Issue by SoloJiang** [raxjs/rax-app#617]
## 背景

SSR CDN 缓存方案中，服务端生成的 HTML 中 `window.__INITIAL_DATA__` 时效性较弱，CSR 每次其实都需要重新请求最新数据，如果默认注入 `window.__INITIAL_DATA__` 会导致 HTML 文件中存在较多冗余数据。

## 方案

app.json：

```json
{
 "injectServerSideData": false
}
```

强制关闭默认注入初始化数据的行为。

**Comment by imsobear** [comment]
serverSideData -> injectServerSideData 是不是更好点？

**Comment by SoloJiang** [comment]
> serverSideData -> injectServerSideData 是不是更好点？

+1

**Comment by SoloJiang** [comment]
#630
