### ISSUE TITLE
[Enhance] 基础依赖升级

### ISSUE THREAD

**Issue by SoloJiang** [raxjs/rax-app#623]
## 样式
- [x] 移除 css-hot-loader
- [ ] 升级 css-loader
- [x] 升级 less
- [x] 升级 less-loader
- [x] 升级 sass-loader
- [ ] 升级 postcss-loader
- [ ] 升级 postcss-safe-parser

## TypeScript

- [x] 升级 ts-loader
- [x] 升级 typescript

## 资源

- [ ] 升级 file-loader
- [ ] 升级 url-loader

## 打包

- [ ] 升级 terser-webpack-plugin

**Comment by imsobear** [comment]
建议分批升级。。。一次这么多有点慌的

**Comment by SoloJiang** [comment]
先升级样式相关的吧

**Comment by SoloJiang** [comment]
其它不重要的依赖暂不考虑升级
