### ISSUE TITLE
SSR下page/home.getInitialProps调用报错时，无法捕获错误后返回null值

### ISSUE THREAD

**Issue by LightGlobal** [raxjs/rax-app#627]
## 发生了什么?

SSR下node端执行page/home.getInitialProps调用报错时，无法捕获错误后返回null值

## 复现步骤，错误日志以及相关配置

yarn init rax <project-name> 初始化支持ssr的应用

## 期望的结果是什么
支持返回null值，这样在服务端异常后，也能继续执行node渲染，并在客户端js处重新执行home.getInitialProps逻辑

## 相关环境信息

- **rax-app 版本**：3.x
- **Node 版本**：10.23.2
- **操作系统**：Mac

**Comment by SoloJiang** [comment]
#626
