### ISSUE TITLE
打印日志方案

### ISSUE THREAD

**Issue by imsobear** [raxjs/rax-app#670]
## What is the current behavior?

自己 console.log，然后上线的时候删除代码

## What is the expected behavior?**

参考：https://ice.work/docs/guide/basic/logger 

## Any additional comments?

- **rax-app Version**：
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by imsobear** [comment]
ice 这个方案可以看下能不能直接用，最好不要依赖 app.js（MPA）大部分都没有，然后看下体积问题。

**Comment by SoloJiang** [comment]
https://github.com/alibaba/ice/issues/4493
https://github.com/alibaba/ice/pull/4497
