### ISSUE TITLE
mpass小程序，通过npx rax-codemod更新后，可以打包成功，小程序内点击上传后报错

### ISSUE THREAD

**Issue by qppq54s** [raxjs/rax-app#693]
## 发生了什么?

使用rax编写的mpass小程序，更新rax3.0版本后，可以编译成功，但无法上传到阿里云mpass发布平台
[错误截图](https://img.alicdn.com/imgextra/i2/O1CN01Fdr1AU1UpjN8TeJPx_!!6000000002567-0-tps-1151-148.jpg)
## 复现步骤，错误日志以及相关配置

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init rax <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。

1. 执行npx rax-codemod 更新rax版本
2. 重新安装依赖
3. npm  run build
4. 在小程序中打开并点击右上角上传按钮

## 期望的结果是什么

可以成功上传（未更新前正常使用）

## 相关环境信息

- **rax-app 版本**：3.0.0
- **build.json 配置**：
```
{
  "targets": [
    "miniapp"
  ],
  "miniapp": {
    "buildType": "compile"
  },
  "inlineStyle": false,
  "plugins": [
    "@ali/build-plugin-rax-app-def"
  ]
}
```
- **Node 版本**：v14.16.0
- **操作系统**：mac os big sur 版本11.2.3

**Comment by ChrisCindy** [comment]
确认一下在 IDE 中打开的是否是 build/miniapp 文件夹？

**Comment by qppq54s** [comment]
> 确认一下在 IDE 中打开的是否是 build/miniapp 文件夹？

是的，更新前我们一直在使用，也能够上传。
更新后，ide中还是能打开并且预览app，就是没有办法上传了。

**Comment by ChrisCindy** [comment]
@qppq54s 换一个原生小程序项目试下看能不能上传。如果也不行，需要联系对应的同学处理一下。目前判断下来不是 Rax 这层的问题。

**Comment by qppq54s** [comment]
> @qppq54s 换一个原生小程序项目试下看能不能上传。如果也不行，需要联系对应的同学处理一下。目前判断下来不是 Rax 这层的问题。

问题找到了，之前src文件夹里面有个public文件夹，这个文件夹被识别成静态资源文件夹了，没有把相关代码编译进去，导致小程序打包上传失败了。
