### ISSUE TITLE
锁版本后 H5 样式存在问题

### ISSUE THREAD

**Issue by zivyangll** [raxjs/rax-app#699]
## What is the current behavior?

使用 npm 锁版本之后，组件自定义 class 被 rax-view 覆盖。复现 demo 已通过钉钉提供，该 issue 用来记录问题进展。

## What is the expected behavior?

期望 H5 样式正常渲染。

## Any additional comments?

- **rax-app Version**：3.4.11
- **build.json Configuration**：
- 
```json
{
  "targets": [
    "web",
    "miniapp",
    "wechat-miniprogram"
  ],
  "plugins": [
    "@ali/build-plugin-rax-app-def"
  ]
}

```
- **Node Version**: v10.17.0
- **Platform**: MacOS

**Comment by ClarkXia** [comment]
## 原因分析

通过 tnpm 安装后的依赖，相同版本的依赖以软链的方式统一指向一个地址，在 css 模块分析的时候为相同的 resolve 地址，因此只会引入一份代码

通过 npm 安装后，rax-view / rax-text 依旧是以各自依赖的方式安装，引入后被识别为不同的 resolve 地址，根据引入顺序依次加载对应 css 文件：
![image](https://user-images.githubusercontent.com/4219965/113962971-5591da80-985b-11eb-8b00-312ab5fcd051.png)

> 生产构建下 会根据压缩 css 将重复样式代码移除

**Comment by zivyangll** [comment]
目前通过统一工程与依赖中的 rax-view 的版本为 rax-view@2 临时解决，还得继续跟进排查～

**Comment by SoloJiang** [comment]
应该和安装方式有关，同一个依赖的相同版本应该共用，用 yarn 试了下没这个问题
