### ISSUE TITLE
app.ts 路由配置为 BrowserRouter 时 运行报错

### ISSUE THREAD

**Issue by ijlghd** [raxjs/rax-app#712]
https://rax.js.org/docs/guide/route 文档里写的是
![image](https://user-images.githubusercontent.com/82920689/115487685-c4bff380-a28b-11eb-859c-ca45b51861c6.png)
我写的
const appConfig = {
  router: {
    type: 'browser'   
  }
};
runApp(appConfig);
项目实际运行时，报错 e is not funtion

**Comment by SoloJiang** [comment]
无法复现这个问题，可以提供一下示例项目
