### ISSUE TITLE
rax-app@3.6.3 版本构建报错

### ISSUE THREAD

**Issue by axuebin** [raxjs/rax-app#772]
## What is the current behavior?

报错信息：

> Module not found: Can't resolve '/Users/axuebin/Code/Work/项目路径/src/pages/OrderConfirm/store' in '/Users/axuebin/Code/Work/项目路径/.rax/pages/OrderConfirm'

导致 ERR! webpack compile error 

## What is the expected behavior?**

正常构建

## Any additional comments?

- **rax-app Version**：3.6.3 （3.6.2 没问题）
- **build.json Configuration**：
- **Node Version**:
- **Platform**:

**Comment by SoloJiang** [comment]
https://github.com/raxjs/rax-app/pull/773

**Comment by SoloJiang** [comment]
The rax-app latest version has rollbacked to 3.6.2. And I have fixed it in v3.6.4 which will release in next Monday.
