### ISSUE TITLE
build-plugin-fusion-mobile能支持配置主题色

### ISSUE THREAD

**Issue by xmsz** [raxjs/rax-app#789]
背景
- 引入了build-plugin-fusion-mobile插件
- 希望可以配置主题色

背景
- 可设置主题色

**Comment by lianmin** [comment]
你好， @xmsz ， 配置主题色的能力，目前还没有开放到公网。 如果希望配置， 需要手动改一下主题 css 文件。

**Comment by xmsz** [comment]
> 你好， @xmsz ， 配置主题色的能力，目前还没有开放到公网。 如果希望配置， 需要手动改一下主题 css 文件。

好的
