### ISSUE TITLE
引入build-plugin-fusion-mobile后，icon的大小不正确

### ISSUE THREAD

**Issue by xmsz** [raxjs/rax-app#790]
背景
- 引入了build-plugin-fusion-mobile
- 然后图标比原来小了1倍
- 其他组件不确定有没有影响

需求
- 如何解决这种情况？

**Comment by xmsz** [comment]
不对 问题不在于`build-plugin-fusion-mobile`

而是icon的样式被rax-view覆盖了...

![image](https://user-images.githubusercontent.com/5879146/126607098-9fde9fc2-332a-4711-bce2-239a536f127b.png)

**Comment by xmsz** [comment]
然后我手动引入`@import '@alifd/meet/es/icon/styles/index.css';`
结果icon组件是正常了
其他组件有问题了

![image](https://user-images.githubusercontent.com/5879146/126607999-a9daf11f-35f1-4d2b-a2c2-3c6009b2790e.png)

这个变得好大

**Comment by SoloJiang** [comment]
`npm ls rax-text` 看下存不存在多版本

**Comment by xmsz** [comment]
> npm ls rax-text

```
├─┬ @alifd/meet@2.4.1
│ ├─┬ rax-icon@1.4.3
│ │ └── rax-text@1.4.0
│ ├─┬ rax-scrollview@3.5.2
│ │ └── rax-text@2.1.2 deduped
│ └── rax-text@1.4.0
├─┬ rax-link@1.5.2
│ └── rax-text@1.4.0
└── rax-text@2.1.2

```

**Comment by SoloJiang** [comment]
有没有复现 demo 来一个看看
