### ISSUE TITLE
本地调试：InitialComponent is not a functio

### ISSUE THREAD

**Issue by Yahiko7** [raxjs/rax-app#794]
## 发生了什么?
本地调试http://127.0.0.1:3333/
Uncaught (in promise) TypeError: InitialComponent is not a function

![image](https://user-images.githubusercontent.com/15901380/126868864-d2f6f08a-4bf2-4b00-bac4-ff61eaf11855.png)

![image](https://user-images.githubusercontent.com/15901380/126868857-ade1d847-cca1-40bd-9c9e-e6186797ec1e.png)

## 复现步骤，错误日志以及相关配置

> 建议并上传到你的 GitHub 仓库，请使用 `yarn init rax <project-name>` 选择 Lite 模板，这样您的问题我们会更高优先级的进行解决。

## 相关环境信息

- **rax-app 版本**：
- **build.json 配置**：
- **Node 版本**：
- **操作系统**：

**Comment by wjq990112** [comment]
相关环境的信息填写一下，建议给一个 demo 以便于调试

**Comment by SoloJiang** [comment]
确认下访问的是不是 app.json 里配置的 path

**Comment by waylon-gmail** [comment]
估计是首页path被改成不是 / ,
如果首页path是 pages/Home/index
那路径得改成 http://127.0.0.1:3333/pages/Home/index

**Comment by SoloJiang** [comment]
对的
