### ISSUE TITLE
@alifd/meet 会开源吗

### ISSUE THREAD

**Issue by yuchonghua** [raxjs/rax-app#796]
@alifd/meet 会开源吗

**Comment by lianmin** [comment]
暂时还不会，我们内部还在使用阶段。 不过 npm 包 和文档都是可以外网访问到的。 

主要是考虑，现在放出来之后，答疑和问题修复进度可能会跟不上节奏

**Comment by waylon-gmail** [comment]
https://github.com/alibaba/rax/issues/2181

Dialog问题能不能先帮忙处理一下，影响挺大的。
