### ISSUE TITLE
Uncaught DOMException: Failed to execute 'setAttribute' on 'Element': '$slots' is not a valid attribute name.

### ISSUE THREAD

**Issue by joseelxg** [raxjs/rax-app#809]
`<Waterfall>
  <view x-slot:header>header</view>
  <view x-slot:item="props">{props.index}: {props.item}</view>
  <view x-slot:footer>footer</view>
</Waterfall>`
使用插槽代码时 报错

**Comment by SoloJiang** [comment]
这是小程序么
