### ISSUE TITLE
[Question/RFC] SSR 场景下如何在嵌套很深的组件里面获取到 query

### ISSUE THREAD

**Issue by fengzilong** [raxjs/rax-app#827]
> 这个 issue 算是半个 Question，半个 RFC 😅

对于同构的场景，`query 获取` 这个功能，既要支持浏览器端，又要支持服务端

- 如果在浏览器中获取 query 很简单，可以使用 location.search
- 但是在 SSR 场景中，需要在 getInitialProps 中透传 ctx.query，然后一层层地传进去（或者使用 context，也很麻烦）

根本原因在于 ctx 只能在 getInitialProps 中拿到，是否可以考虑增加一个 hook，`useSSRContext`

用法类似

`hooks/use-query.js`

```js
import { useSSRContext } from 'rax-app'

export default () => {
  const ctx = useSSRContext()

  if ( isWeb ) { return ... }

  return ctx.query || {}
}
```

其他比如 `获取 userAgent` 也有类似的需求

**Comment by SoloJiang** [comment]
后续版本会支持通过 `getSearchParams` 获取到 parse 之后的参数

**Comment by imsobear** [comment]
getInitialData 可以承载这个需求吧？ @SoloJiang

**Comment by fengzilong** [comment]
> 后续版本会支持通过 `getSearchParams` 获取到 parse 之后的参数

query 这个解法没问题的，但是类似的问题还是没有解决，比如同构获取 userAgent，实际场景中还有一些其他字段需要从 ctx 上获取，而且我们希望可以自己提取出一些公共的同构方法

比如 useUserAgent、useSupportWebp、useIsWechatApp 等 hook，以及我们网关在 ctx 上带的 ctx.req.headers['x-user-id']，也抽出 useUserId 的 hook

支持 useSSRContext 后面 rax 内部的 getSearchParams 实现也可以用这个（我猜的），这个会相对通用一些

**Comment by fengzilong** [comment]
> getInitialData 应该可以承载这个需求，不过这样的话入口必须用 runApp。

这个没听太懂，没怎么用过 runApp…

**Comment by SoloJiang** [comment]
getInitialData 可以给全局 store 返回一个初始的 initialState，利用状态管理的能力就可以获取到这个状态

**Comment by SoloJiang** [comment]
后续版本内会大幅降低写 runApp 带来的副作用

**Comment by imsobear** [comment]
### 获取应用初始化数据

在 `src/app.ts` 中可通过 `app.getInitialData()` 获取全局数据：

```diff
import { runApp, request } from 'ice';

const appConfig = {
+  app: {
+    getInitialData: async (ctx) => {
+      // const data = await request.get('/api/data');
+      return {
+       foo: 'bar',
+       initialStates: {
+         user: { name: 'Jack', id: '01' }
+       }
+      };
+    }
+  },
};

runApp(appConfig);
```

### 消费应用初始化数据

框架提供了两种方式获取 `app.getInitialData()` 返回的数据：

#### 通过 `getInitialData()` 消费

```ts
import React from 'react';
import { getInitialData } from 'ice';

export default = () => {
  const { foo } = getInitialData();
  console.log(initialData);  // => bar
};
```

#### 作为 store 的初始化状态

`app.getInitialData()` 返回的 `initialStates` 字段会作为 store 的初始状态，比如 `models/user.js` 的默认 states 即上述的 `{ name: 'Jack', id: '01' }`，可以直接在 View 中使用：

```jsx
import store from '@/store';
const HomePage = () => {
  const [userState, userDispatchers] = store.useModel('user');
  console.log(userState.name); // => Jack
  return <>{userState.name}</>;
}
```

**Comment by imsobear** [comment]
> getInitialData 可以给全局 store 返回一个初始的 initialState，利用状态管理的能力就可以获取到这个状态

不仅是 initialStates，还有一个独立的 `getInitialData()` API，如上复制的文档。
