### ISSUE TITLE
[Feature] expect stylus to be supported

### ISSUE THREAD

**Issue by fengxinming** [raxjs/rax-app#831]
expect stylus to be supported in Rax App

**Comment by SoloJiang** [comment]
I don't see much need for Rax App to support stylus. In the future, we prefer developers to use vanilla css.

**Comment by fengxinming** [comment]
@SoloJiang I was aware that you are not heading to support stylus, so I have pushed a PR https://github.com/raxjs/rax-app/pull/832

**Comment by SoloJiang** [comment]
If I merge your pr, developers will think rax-app should support stylus. In the future, stylus-loader updated or other break change, rax-app will be affected.

**Comment by SoloJiang** [comment]
The conclusion: you should develop a custom build scripts plugin, when you have to use stylus in your project.
