### ISSUE TITLE
Rax App 3.8.0 next 版本问题记录

### ISSUE THREAD

**Issue by SoloJiang** [raxjs/rax-app#834]
- [x] 底层和 icejs2.0 融合
  - [x] MPA
  - [x] SPA #791 
  - [x] SSR
  - [x] TabBar 渲染 
  - [x] 兼容补充 terserOptions
- [x] 一键切换 webpack5
  - [x] 所有端的构建逻辑兼容 webpack4 & webpack5
  - [x] copy-webpack-plugin 升级（解决 webpack5 warning 问题，验证高版本在小程序报错的问题） 
- [x] 日志方案
- [x] 接入 swc
   - [x] 构建能力
   - [x] 多端代码移除（需通过 rust 扩展这部分的能力）  
- [x] postcss 生态系列兼容 webpack5 @wjq990112 
- [x] 更友好的信息提示 @SoloJiang 
   - [x] MPA 和小程序共存报错提示
   - [x] 开启 swc 的时候提示暂不支持小程序和 JSX+
   - [x] swc 暂时不支持 inlineStyle（先看下实现成本）
- [x] SSR MPA `getInitialProps` 未执行 @SoloJiang 
- [x] 确保内网插件可以正常运行 @SoloJiang 
- [ ] 文档  @SoloJiang @wjq990112 

### 待验证场景

- [x] Web SPA & document 模式
   - [x] 普通渲染
   - [x] 分页面配置懒加载能力
   - [x] 分页面配置保活能力
- [x] Web MPA & document 模式
- [x] PHA & document 模式
- [x] kraken
- [x] 小程序普通模式/双引擎
- [x] 小程序分包
- [x] SSR
- [x] 代码体积问题
- [x] windows @wjq990112 
- [x] 状态管理

**Comment by SoloJiang** [comment]
相关发布 PR: #603

**Comment by cryzzchen** [comment]
BUG：getValue('staticConfig') 拿到的值不是 app.json 中的原始配置
表现：

```json
// app.json
{
  "routes": [
    {
      "path": "/",
      "source": "pages/Home/index",
      "spm": "24863359",
      "miniappMain": true
    }
  ]
}
```
3.8.0-rc 版本中，getValue('staticConfig') 的值如下：
```json
// app.json
{
  "routes": [
    {
      "path": "/",
      "source": "pages/Home/index",
      "spm": "24863359",
      "miniappMain": true，
      “name”: "pages/Home/index",
      "entryName": "pages/Home/index"
    }
  ]
}
```

**Comment by cryzzchen** [comment]
优化：跨端应用（指跨 web 和 小程序）中，若用户设置 web 为 `mpa: true` 或 `pha: true` 时，应当在构建时增加提示跨端应用中 web 必须为 SPA。

**Comment by cryzzchen** [comment]
问题：运行时小程序的执行顺序发生了变化，原本业务代码会在 Page.onLoad 生命周期中执行，现在会在 App.onLaunch 生命周期中执行，导致诸如 getApp() 之类无法在 App.onLaunch 中生效的 API 执行出错。

**Comment by SoloJiang** [comment]
优化：开启 swc 的时候，要提示不支持小程序和 JSX+

**Comment by SoloJiang** [comment]
兼容页面文件名不规范导致的报错，例如 `List-a`

**Comment by SoloJiang** [comment]
插件执行顺序，pha 和 ssr 需要移到后面执行，避免新注册的 task 覆盖了 ssr devServer 的配置
