### ISSUE TITLE
[RFC] 小程序 development 模式开启 minify 能力

### ISSUE THREAD

**Issue by SoloJiang** [raxjs/rax-app#859]
# 概述

小程序对代码体积有严格控制，在 dev 阶段如果超出体积限制将会禁止真机预览等相关能力。所以调试小程序的时候，需要提供开关能够在 dev 阶段压缩代码。

# 背景

在 rax-app 3.7.0 之前的版本，我们允许设置 `minify: true` 即表示开发者在任一模式下均希望开启代码压缩能力。

但是在 rax-app 3.7.0 之后的版本，`minify` 的能力得到了扩充，允许开发者指定压缩工具，即：

```json
{
  "minify": {
    "type": "esbuild"
  }
}
```

此时，无法判断开发者是否想强制开启代码压缩的能力。所以本 RFC 希望针对小程序的这个场景扩充 `minify` 字段来强制开启压缩能力。

# 方案详述

```json
{
  "minify": {
    "activeInDev": ["web", "miniapp"]
  }
}
```

当配置 `minify: true` 时，所有任务都会开启压缩。

- 小程序场景，dev 阶段开启压缩能力可以减小体积，达到 IDE 预览阈值
- 其它端场景，dev 阶段开启压缩能力可以在本地快速调试压缩后代码，定位线上可能出现的问题

**Comment by SoloJiang** [comment]
个人倾向于方案 1 的命名

**Comment by fengzilong** [comment]
比较倾向于

```js
{
  minify: {
    "forceInDev": true,
    "type": "esbuild"
  }
}
```

按照上面 RFC 里的做法，后面 build.json 新增字段会越来越多，很多平台相关的配置都会出现在 `根配置` 下

比如 miniappXXX、webXXX、phaXXX，这些平台只是插件，感觉不应该影响根配置
